/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fst.formation.app;


import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author rassil
 */
public class Choix_form extends javax.swing.JFrame {

private int id_emp=1;

    public Choix_form(int x) {
        initComponents();
        this.id_emp=x;
         remplir();
        setLocationRelativeTo(null);
    }
    
    public void changemenu(String s){
    jMenu1.setText(s);
    }
    
    //public void setidform(int x){id_form=x;}
    
    public void remplir(){

        String sql="select formation.id_form from formation INNER JOIN session INNER JOIN inscrit ON session.id_form=formation.id_form AND session.id_sess=inscrit.id_sess where inscrit.id_emp="+id_emp;
        Vector<Integer> vsess=new Vector<>();
        ResultSet rs=Rselect.select(sql);  
        
        try{
          while(rs.next()){
           vsess.add( rs.getInt(1) );
           
            }
        
        }catch(SQLException ex){
        JOptionPane.showMessageDialog(this, ex);
        } 
        
     
          String sql1="select * from formation";
        
        
            
         if(!vsess.isEmpty())
         {
                 sql1+=" where id_form NOT Like '"+vsess.elementAt(0)+"'";
            for(int i=1;i<vsess.size()-2;i++){
               
               sql1+=" AND id_form NOT Like '"+vsess.elementAt(i)+"' ";            
            }
            sql1+=" AND id_form NOT Like '"+vsess.lastElement()+"' "; 
            
         }   
        else System.out.println("Empty");
       
        
        System.out.println(sql1);
        
        
        

          
       ResultSet rs1=Rselect.select(sql1);
        form_tab.setModel(DbUtils.resultSetToTableModel(rs1));
        

    

    
    
    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        form_tab = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jInscri = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion Formation");
        setResizable(false);

        form_tab.setFont(new java.awt.Font("Palatino Linotype", 1, 12));
        form_tab = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;   //Disallow the editing of any cell
            }
        };
        form_tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        form_tab.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        form_tab.getTableHeader().setReorderingAllowed(false);
        form_tab.setUpdateSelectionOnSort(false);
        form_tab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                form_tabMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(form_tab);

        jLabel1.setText("Liste des Formations disponibles");

        jInscri.setText("Choisir Formation");
        jInscri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInscriActionPerformed(evt);
            }
        });

        jMenu1.setText("Utilisateur");

        jMenuItem1.setText("Déconnecter");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Option");

        jMenuItem2.setText("Quitter");
        jMenuItem2.setToolTipText("");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jInscri)))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jInscri)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void form_tabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_form_tabMouseClicked

    }//GEN-LAST:event_form_tabMouseClicked

    private void jInscriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInscriActionPerformed
       ouvrir_session(id_emp);
    }//GEN-LAST:event_jInscriActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new Login().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
                this.dispose();

    }//GEN-LAST:event_jMenuItem2ActionPerformed
    
     private void ouvrir_session(int x) {
         
         int i=form_tab.getSelectedRow();
         if (i!=-1)
         {
             
             int id=(int) form_tab.getValueAt(i,0);
             System.out.println(id);
             Session ses=new Session();
             ses.setid(id);
             ses.setidemp(x);
             ses.remplir(id);
             this.hide();
             ses.setVisible(true);
             
         
         }else JOptionPane.showMessageDialog(this,"Choisir une formation");
         
         
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Choix_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Choix_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Choix_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Choix_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        new Choix_form(1).setVisible(true);
        /* Create and display the form */
  
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable form_tab;
    private javax.swing.JButton jInscri;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

   
}
